//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhadsCarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public CarModel()
        {
            this.FleetCars = new HashSet<FleetCar>();
        }
    
        public int CarModelID { get; set; }
        public int ManufacturerModelID { get; set; }
        public int ProductionYear { get; set; }
        public bool ManualGear { get; set; }
        public decimal DailyPrice { get; set; }
        public decimal DayDelayPrice { get; set; }
    
        public virtual ManufacturerModel ManufacturerModel { get; set; }
        public virtual ICollection<FleetCar> FleetCars { get; set; }
    }
}
