//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhadsCarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Manufacturer()
        {
            this.ManufacturerModels = new HashSet<ManufacturerModel>();
        }
    
        public int ManufacturerID { get; set; }
        public string ManufacturerName { get; set; }
    
        public virtual ICollection<ManufacturerModel> ManufacturerModels { get; set; }
    }
}
