//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhadsCarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturerModel
    {
        public ManufacturerModel()
        {
            this.CarModels = new HashSet<CarModel>();
        }
    
        public int ManufacturerModelID { get; set; }
        public string ManufacturerModelName { get; set; }
        public int ManufacturerID { get; set; }
    
        public virtual ICollection<CarModel> CarModels { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
