//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhadsCarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int RentalID { get; set; }
        public string LicensePlate { get; set; }
        public int UserID { get; set; }
        public System.DateTime PickUpDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
    
        public virtual FleetCar FleetCar { get; set; }
        public virtual User User { get; set; }
    }
}
